---
name: Reg-ER-100 
cpu: Yes
root_dir: .

data: # Data related parameters
    num_examples_train: 20000
    #num_examples_test: 1000
    num_examples_val: 1000
    generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
    noise_model: ErdosRenyi
    edge_density: 0.2
    n_vertices: 25
    vertex_proba: 1. # Parameter of the binomial distribution of vertices
    noise: 0.05
    path_dataset: dataset # Path where datasets are stored

train: # Training parameters
    epoch: 50
    batch_size: 16
    lr: !!float 1e-4
    scheduler_step: 5
    scheduler_decay: 0.9
    print_freq: 100
    # How to reduce the loss over several examples:
    # mean, mean_of_mean
    loss_reduction: mean

arch: # Architecture and model
    arch: Siamese_Model
    model_name: Simple_Node_Embedding
    num_blocks: 2
    original_features_num: 2
    in_features: 64
    out_features: 64
    depth_of_mlp: 3

observers:
    neptune:
        enable: Yes
        project: mlelarge/GCP-RegBin
